//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ImageProducts = new HashSet<ImageProduct>();
        }
    
        public long F1 { get; set; }
        public string F2 { get; set; }
        public Nullable<long> F3 { get; set; }
        public Nullable<bool> F4 { get; set; }
        public string F5 { get; set; }
        public string F6 { get; set; }
        public string F7 { get; set; }
        public string F8 { get; set; }
        public string F9 { get; set; }
        public Nullable<System.DateTime> F10 { get; set; }
        public string F11 { get; set; }
        public string F12 { get; set; }
        public string F13 { get; set; }
        public string F14 { get; set; }
        public Nullable<int> F15 { get; set; }
        public Nullable<int> F16 { get; set; }
        public Nullable<int> F17 { get; set; }
        public Nullable<int> F18 { get; set; }
        public string F19 { get; set; }
        public Nullable<double> lon1 { get; set; }
        public Nullable<double> lat1 { get; set; }
        public string F20 { get; set; }
        public Nullable<double> lon2 { get; set; }
        public Nullable<double> lat2 { get; set; }
        public Nullable<int> F21 { get; set; }
        public string F22 { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageProduct> ImageProducts { get; set; }
        public virtual Local Local { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
